services:
  app:
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: asietex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
